clc
clear
close all

% ============================================================
% Add required folders to MATLAB path
% ============================================================
addpath('../integrators','../phipmsimuliom','./Data')

% ============================================================
% Folder for numerical results and figures
% ============================================================
results_dir = './Test_results';

if ~exist(results_dir,'dir')
    mkdir(results_dir);
end

% ============================================================
% Parameters
% ============================================================

% eps_list  = [0.1];
% eps_names = {'0_1'};

eps_list  = [0.015];
eps_names = {'0_015'};

N = [16,32,64,128].*2;

% ============================================================
% Loop over epsilon
% ============================================================
for k = 1:length(eps_list)

    epsilon = eps_list(k);

    fprintf('\n==============================\n');
    fprintf('Running for epsilon = %.3f\n',epsilon);
    fprintf('==============================\n');

    % --------------------------------------------------------
    % Time interval
    % --------------------------------------------------------
    s = 3/(sqrt(2)*epsilon);
    tspan = [0,3/(4*s)];

    % --------------------------------------------------------
    % Space discretization on Omega = [-0.5,1.5]^2
    % --------------------------------------------------------
    n = 128;

    xL = -0.5;
    xR = 1.5;

    yL = -0.5;
    yR = 1.5;

    dx = (xR-xL)/n;
    dy = (yR-yL)/n;

    x = linspace(xL,xR,n+1);
    y = linspace(yL,yR,n+1);

    [X,Y] = meshgrid(x,y);

    X = X';
    Y = Y';

    % ========================================================
    % Initial condition
    % ========================================================
    initial_condition = ...
        0.5*(1-tanh(X/(2*sqrt(2)*epsilon)));

    U0 = reshape( ...
        initial_condition, ...
        (n+1)*(n+1),1);

    % ========================================================
    % Nonlinearity
    % ========================================================
    g = @(u) ...
        (1/epsilon^2)*u ...
        - (1/epsilon^2)*u.^3;

    deriv_g = @(u) ...
        (1/epsilon^2) ...
        - 3*(1/epsilon^2)*u.^2;

    % ========================================================
    % Spatial discretization
    % ========================================================
    I = speye(n+1);
    e = ones(n+1,1);

    % --------------------------------------------------------
    % 1D Neumann Laplacian
    % --------------------------------------------------------
    Tx = spdiags( ...
        [e -2*e e], ...
        [-1 0 1], ...
        n+1,n+1);

    Tx(1,2)       = 2;
    Tx(end,end-1) = 2;

    Ty = spdiags( ...
        [e -2*e e], ...
        [-1 0 1], ...
        n+1,n+1);

    Ty(1,2)       = 2;
    Ty(end,end-1) = 2;

    % --------------------------------------------------------
    % 2D Laplacian with zero Neumann boundary conditions
    % --------------------------------------------------------
    A = kron(I,Tx)/dx^2 ...
      + kron(Ty,I)/dy^2;

    % ========================================================
    % Semilinear system
    % ========================================================
    F = @(u) A*u + g(u);

    J = @(u) ...
        spdiags( ...
            deriv_g(u), ...
            0, ...
            (n+1)^2, ...
            (n+1)^2);

    % ========================================================
    % Load exact/reference solution
    % ========================================================
    fname = ...
        ['128_exac_sol_AllenCahn_' eps_names{k} '.mat'];

    data_fname = fullfile('./Data',fname);

    if exist(data_fname,'file')
        S = load(data_fname);
    else
        S = load(fname);
    end

    if isfield(S,'exac_sol')

        exac_sol = S.exac_sol;

    else

        vars = fieldnames(S);
        exac_sol = S.(vars{1});

    end

    % Make sure reference solution is a column vector
    exac_sol = exac_sol(:);

    % ========================================================
    % Preallocate errors
    % ========================================================
    expHR3_err    = zeros(1,length(N));
    expHR42_err   = zeros(1,length(N));
    expHR4s3_err  = zeros(1,length(N));

    expH3_err     = zeros(1,length(N));
    expH42_err    = zeros(1,length(N));
    expH4s3_err   = zeros(1,length(N));

    expRB32_err   = zeros(1,length(N));
    expRB42_err   = zeros(1,length(N));
    expRB43_err   = zeros(1,length(N));
    pexpRB43_err  = zeros(1,length(N));

    % ========================================================
    % Preallocate CPU times
    % ========================================================
    expHR3_cpu    = zeros(1,length(N));
    expHR42_cpu   = zeros(1,length(N));
    expHR4s3_cpu  = zeros(1,length(N));

    expH3_cpu     = zeros(1,length(N));
    expH42_cpu    = zeros(1,length(N));
    expH4s3_cpu   = zeros(1,length(N));

    expRB32_cpu   = zeros(1,length(N));
    expRB42_cpu   = zeros(1,length(N));
    expRB43_cpu   = zeros(1,length(N));
    pexpRB43_cpu  = zeros(1,length(N));

    % ========================================================
    % Number of time steps used for CPU/error comparison
    % ========================================================
    N_expHR3 = ...
        [20 34 78 175];

    N_expHR42 = ...
        [21 37 65 116];

    N_expHR4s3 = ...
        [19 33 58 105];

    N_expRB32 = ...
        [35 70 140 290];

    N_expRB42 = ...
        [29 50 90 160];

    N_expRB43 = ...
        [21 39 70 125];

    N_pexpRB43 = ...
        N_expRB42;

    N_expH3 = ...
        [58 134 300 650];

    N_expH42 = ...
        [38 75 140 250];

    N_expH4s3 = ...
        [38 75 140 250];

    % ========================================================
    % Time integration
    % ========================================================
    for i = 1:length(N)

        fprintf('\n-----------------------------------\n');
        fprintf('epsilon = %.3f, index = %d/%d\n', ...
            epsilon,i,length(N));
        fprintf('-----------------------------------\n');

        % ----------------------------------------------------
        % expHR3
        % ----------------------------------------------------
        [~,expHR3_sol,expHR3_cpu(i)] = ...
            expHR3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expHR3(i), ...
                1e-10,0.45);

        expHR3_err(i) = ...
            norm(exac_sol-expHR3_sol(:),'inf');

        % ----------------------------------------------------
        % expHR4s2
        % ----------------------------------------------------
        [~,expHR42_sol,expHR42_cpu(i)] = ...
            expHR3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expHR42(i), ...
                1e-10,0.5);

        expHR42_err(i) = ...
            norm(exac_sol-expHR42_sol(:),'inf');

        % ----------------------------------------------------
        % expHR4s3
        % ----------------------------------------------------
        [~,expHR4s3_sol,expHR4s3_cpu(i)] = ...
            expHR4s3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expHR4s3(i), ...
                1e-10,[0.1,0.6]);

        expHR4s3_err(i) = ...
            norm(exac_sol-expHR4s3_sol(:),'inf');

        % ----------------------------------------------------
        % expRB32
        % ----------------------------------------------------
        [~,expRB32_sol,expRB32_cpu(i)] = ...
            expRB32( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N_expRB32(i), ...
                1e-10);

        expRB32_err(i) = ...
            norm(exac_sol-expRB32_sol(:),'inf');

        % ----------------------------------------------------
        % expRB42
        % ----------------------------------------------------
        [~,expRB42_sol,expRB42_cpu(i)] = ...
            expRB42( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N_expRB42(i), ...
                1e-10);

        expRB42_err(i) = ...
            norm(exac_sol-expRB42_sol(:),'inf');

        % ----------------------------------------------------
        % expRB43
        % ----------------------------------------------------
        [~,expRB43_sol,expRB43_cpu(i)] = ...
            expRB43( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N_expRB43(i), ...
                1e-10);

        expRB43_err(i) = ...
            norm(exac_sol-expRB43_sol(:),'inf');

        % ----------------------------------------------------
        % pexpRB43
        % ----------------------------------------------------
        [~,pexpRB43_sol,pexpRB43_cpu(i)] = ...
            pexpRB43( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N_pexpRB43(i), ...
                1e-10);

        pexpRB43_err(i) = ...
            norm(exac_sol-pexpRB43_sol(:),'inf');

        % ----------------------------------------------------
        % expH3
        % ----------------------------------------------------
        [~,expH3_sol,expH3_cpu(i)] = ...
            expH3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expH3(i), ...
                1e-10,1/3);

        expH3_err(i) = ...
            norm(exac_sol-expH3_sol(:),'inf');

        % ----------------------------------------------------
        % expH4s2
        % ----------------------------------------------------
        [~,expH42_sol,expH42_cpu(i)] = ...
            expH3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expH42(i), ...
                1e-10,1/2);

        expH42_err(i) = ...
            norm(exac_sol-expH42_sol(:),'inf');

        % ----------------------------------------------------
        % expH4s3
        % ----------------------------------------------------
        [~,expH4s3_sol,expH4s3_cpu(i)] = ...
            expH4s3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expH4s3(i), ...
                1e-10,[0.35,0.8]);

        expH4s3_err(i) = ...
            norm(exac_sol-expH4s3_sol(:),'inf');

        fprintf('epsilon = %.3f, index = %d done\n', ...
            epsilon,i);

    end

    % ========================================================
    % Minimum and maximum errors
    % ========================================================
    min_err = [ ...
        min(expHR3_err), ...
        min(expHR42_err), ...
        min(expHR4s3_err), ...
        min(expH3_err), ...
        min(expH42_err), ...
        min(expH4s3_err), ...
        min(expRB32_err), ...
        min(expRB42_err), ...
        min(expRB43_err), ...
        min(pexpRB43_err) ...
    ];

    max_err = [ ...
        max(expHR3_err), ...
        max(expHR42_err), ...
        max(expHR4s3_err), ...
        max(expH3_err), ...
        max(expH42_err), ...
        max(expH4s3_err), ...
        max(expRB32_err), ...
        max(expRB42_err), ...
        max(expRB43_err), ...
        max(pexpRB43_err) ...
    ];

    % ========================================================
    % Save all CPU/error data
    % ========================================================
    data_file = fullfile( ...
        results_dir, ...
        ['Allencahn_CPU_data_128_eps_' eps_names{k} '.mat']);

    save(data_file, ...
        'epsilon', ...
        'n', ...
        'dx', ...
        'dy', ...
        'tspan', ...
        'N', ...
        ...
        'N_expHR3', ...
        'N_expHR42', ...
        'N_expHR4s3', ...
        'N_expH3', ...
        'N_expH42', ...
        'N_expH4s3', ...
        'N_expRB32', ...
        'N_expRB42', ...
        'N_expRB43', ...
        'N_pexpRB43', ...
        ...
        'expHR3_err', ...
        'expHR42_err', ...
        'expHR4s3_err', ...
        'expH3_err', ...
        'expH42_err', ...
        'expH4s3_err', ...
        'expRB32_err', ...
        'expRB42_err', ...
        'expRB43_err', ...
        'pexpRB43_err', ...
        ...
        'expHR3_cpu', ...
        'expHR42_cpu', ...
        'expHR4s3_cpu', ...
        'expH3_cpu', ...
        'expH42_cpu', ...
        'expH4s3_cpu', ...
        'expRB32_cpu', ...
        'expRB42_cpu', ...
        'expRB43_cpu', ...
        'pexpRB43_cpu', ...
        ...
        'min_err', ...
        'max_err');

    fprintf('\nCPU/error data saved to:\n%s\n',data_file);

    % ========================================================
    % Display CPU times and errors
    % ========================================================
    fprintf('\n=============================================\n');
    fprintf('CPU/Error results for epsilon = %.3f\n',epsilon);
    fprintf('=============================================\n');

    fprintf('\nMethod          Min Error       Max Error\n');
    fprintf('---------------------------------------------\n');

    method_names = { ...
        'expHR3', ...
        'expHR42', ...
        'expHR4s3', ...
        'expH3', ...
        'expH42', ...
        'expH4s3', ...
        'expRB32', ...
        'expRB42', ...
        'expRB43', ...
        'pexpRB43'};

    for j = 1:length(method_names)

        fprintf('%-12s  %12.4e   %12.4e\n', ...
            method_names{j}, ...
            min_err(j), ...
            max_err(j));

    end

    % ========================================================
    % CPU versus error plot
    % ========================================================
    fig = figure(k);

    set(fig,'Units','inches');
    set(fig,'Position',[1 1 6.8 5.2]);
    set(fig,'PaperPositionMode','auto');

    semilogy( ...
        expHR3_cpu,expHR3_err, ...
        'o-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    hold on

    semilogy( ...
        expHR42_cpu,expHR42_err, ...
        'o-', ...
        'LineWidth',1, ...
        'MarkerSize',12);

    semilogy( ...
        expHR4s3_cpu,expHR4s3_err, ...
        'v-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    semilogy( ...
        expH3_cpu,expH3_err, ...
        '>-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    semilogy( ...
        expH42_cpu,expH42_err, ...
        '>-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    semilogy( ...
        expH4s3_cpu,expH4s3_err, ...
        '<-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    semilogy( ...
        expRB32_cpu,expRB32_err, ...
        '^-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    semilogy( ...
        expRB42_cpu,expRB42_err, ...
        '^-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    semilogy( ...
        expRB43_cpu,expRB43_err, ...
        'd-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    semilogy( ...
        pexpRB43_cpu,pexpRB43_err, ...
        's-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    % ========================================================
    % Axis labels
    % ========================================================
    xlabel('CPU time')
    ylabel('Error')

    grid on
    box on

    % ========================================================
    % Axis settings
    % ========================================================
    ax = gca;

    ax.Units = 'normalized';
    ax.Position = [0.24 0.16 0.72 0.72];

    set(ax, ...
        'TickLength', ...
        2*get(ax,'TickLength'));

    axis square

    % ========================================================
    % Legend
    % ========================================================
    if k == length(eps_list)

        lgd = legend( ...
            'expHR3s2', ...
            'expHR4s2', ...
            'expHR4s3', ...
            'expH3', ...
            'expH4s2', ...
            'expH4s3', ...
            'exprb32', ...
            'exprb42', ...
            'exprb43', ...
            'pexprb43', ...
            'Location','westoutside');

        lgd.FontSize = 10;

    else

        legend off

    end

    % ========================================================
    % Save CPU figure
    % ========================================================
    fig_base = fullfile( ...
        results_dir, ...
        ['Allencahn_CPU34_128_eps_' eps_names{k}]);

    % EPS
    print( ...
        fig, ...
        fig_base, ...
        '-depsc');


    fprintf('\nCPU figure saved to:\n%s\n',results_dir);

end

% ============================================================
% Remove paths
% ============================================================
rmpath( ...
    '../integrators', ...
    '../phipmsimuliom', ...
    './Data');

fprintf('\n=============================================\n');
fprintf('All CPU computations finished.\n');
fprintf('Results are stored in:\n');
fprintf('%s\n',results_dir);
fprintf('=============================================\n');