clc
clear
close all

% ============================================================
% Add required folders to MATLAB path
% ============================================================
addpath('../integrators','../phipmsimuliom','./Data')

% ============================================================
% Folder for numerical results and figures
% ============================================================
results_dir = './Test_results';

if ~exist(results_dir,'dir')
    mkdir(results_dir);
end

% ============================================================
% Parameters
% ============================================================
eps_list  = [0.1,0.015];
eps_names = {'0_1','0_015'};

N = [16,32,64,128].*2;    % Number of time steps
h = 1./N;                  % Used for convergence plots

% ============================================================
% Loop over epsilon
% ============================================================
for k = 1:length(eps_list)

    epsilon = eps_list(k);

    fprintf('\n==============================\n');
    fprintf('Running for epsilon = %.3f\n', epsilon);
    fprintf('==============================\n');

    % --------------------------------------------------------
    % Time interval
    % --------------------------------------------------------
    s = 3/(sqrt(2)*epsilon);
    tspan = [0, 3/(4*s)];

    % --------------------------------------------------------
    % Space discretization on Omega = [-0.5,1.5]^2
    % --------------------------------------------------------
    n  = 128;

    xL = -0.5;
    xR = 1.5;

    yL = -0.5;
    yR = 1.5;

    dx = (xR - xL)/n;
    dy = (yR - yL)/n;

    x = linspace(xL, xR, n+1);
    y = linspace(yL, yR, n+1);

    [X,Y] = meshgrid(x,y);

    X = X';
    Y = Y';

    % --------------------------------------------------------
    % Initial condition
    % --------------------------------------------------------
    initial_condition = ...
        0.5 * (1 - tanh(X/(2*sqrt(2)*epsilon)));

    U0 = reshape(initial_condition,(n+1)*(n+1),1);

    % --------------------------------------------------------
    % Allen-Cahn nonlinearity
    % --------------------------------------------------------
    g = @(u) ...
        (1/epsilon^2)*u ...
        - (1/epsilon^2)*u.^3;

    deriv_g = @(u) ...
        (1/epsilon^2) ...
        - 3*(1/epsilon^2)*u.^2;

    % --------------------------------------------------------
    % Spatial discretization
    % --------------------------------------------------------
    I = speye(n+1);
    e = ones(n+1,1);

    % --------------------------------------------------------
    % 1D Neumann Laplacian in x-direction
    % --------------------------------------------------------
    Tx = spdiags([e -2*e e],[-1 0 1],n+1,n+1);

    Tx(1,2)       = 2;
    Tx(end,end-1) = 2;

    % --------------------------------------------------------
    % 1D Neumann Laplacian in y-direction
    % --------------------------------------------------------
    Ty = spdiags([e -2*e e],[-1 0 1],n+1,n+1);

    Ty(1,2)       = 2;
    Ty(end,end-1) = 2;

    % --------------------------------------------------------
    % 2D Laplacian with zero Neumann boundary conditions
    % --------------------------------------------------------
    A = kron(I,Tx)/dx^2 ...
      + kron(Ty,I)/dy^2;

    % --------------------------------------------------------
    % Semilinear system
    %
    %     u' = A*u + g(u)
    % --------------------------------------------------------
    F = @(u) A*u + g(u);

    J = @(u) ...
        spdiags(deriv_g(u),0,(n+1)^2,(n+1)^2);

    % ========================================================
    % Load exact/reference solution
    % ========================================================
    fname = ...
        ['128_exac_sol_AllenCahn_' eps_names{k} '.mat'];

    data_fname = fullfile('./Data',fname);

    if exist(data_fname,'file')
        S = load(data_fname);
    else
        % Fallback in case Data has already been added to path
        S = load(fname);
    end

    if isfield(S,'exac_sol')

        exac_sol = S.exac_sol;

    else

        vars = fieldnames(S);

        exac_sol = S.(vars{1});

    end

    % Make sure reference solution is a column vector
    exac_sol = exac_sol(:);

    % ========================================================
    % Preallocate errors
    % ========================================================
    expHR3_err    = zeros(1,length(N));
    expHR42_err   = zeros(1,length(N));
    expHR4s3_err  = zeros(1,length(N));

    expH3_err     = zeros(1,length(N));
    expH42_err    = zeros(1,length(N));
    expH4s3_err   = zeros(1,length(N));

    expRB32_err   = zeros(1,length(N));
    expRB42_err   = zeros(1,length(N));
    expRB43_err   = zeros(1,length(N));
    pexpRB43_err  = zeros(1,length(N));

    % ========================================================
    % Time integration
    % ========================================================
   % data_file = fullfile( ...
   %  results_dir, ...
   %  ['Allencahn_data_128_eps_' eps_names{k} '.mat']);
   % 
   %  load(data_file);
    for i = 1:length(N)

        fprintf('\n-----------------------------------\n');
        fprintf('epsilon = %.3f, N = %d\n', ...
            epsilon,N(i));
        fprintf('-----------------------------------\n');

        % ----------------------------------------------------
        % expHR3
        % ----------------------------------------------------
        [~,expHR3_sol] = ...
            expHR3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10,0.45);

        expHR3_err(i) = ...
            norm(exac_sol-expHR3_sol(:),'inf');

        % ----------------------------------------------------
        % expHR4s2
        % ----------------------------------------------------
        [~,expHR42_sol] = ...
            expHR3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10,0.5);

        expHR42_err(i) = ...
            norm(exac_sol-expHR42_sol(:),'inf');

        % ----------------------------------------------------
        % expHR4s3
        % ----------------------------------------------------
        [~,expHR4s3_sol] = ...
            expHR4s3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10,[0.1,0.6]);

        expHR4s3_err(i) = ...
            norm(exac_sol-expHR4s3_sol(:),'inf');

        % ----------------------------------------------------
        % expRB32
        % ----------------------------------------------------
        [~,expRB32_sol] = ...
            expRB32( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10);

        expRB32_err(i) = ...
            norm(exac_sol-expRB32_sol(:),'inf');

        % ----------------------------------------------------
        % expRB42
        % ----------------------------------------------------
        [~,expRB42_sol] = ...
            expRB42( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10);

        expRB42_err(i) = ...
            norm(exac_sol-expRB42_sol(:),'inf');

        % ----------------------------------------------------
        % expRB43
        % ----------------------------------------------------
        [~,expRB43_sol] = ...
            expRB43( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10);

        expRB43_err(i) = ...
            norm(exac_sol-expRB43_sol(:),'inf');

        % ----------------------------------------------------
        % pexpRB43
        % ----------------------------------------------------
        [~,pexpRB43_sol] = ...
            pexpRB43( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10);

        pexpRB43_err(i) = ...
            norm(exac_sol-pexpRB43_sol(:),'inf');

        % ----------------------------------------------------
        % expH3
        % ----------------------------------------------------
        [~,expH3_sol] = ...
            expH3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10,1/3);

        expH3_err(i) = ...
            norm(exac_sol-expH3_sol(:),'inf');

        % ----------------------------------------------------
        % expH4s2
        % ----------------------------------------------------
        [~,expH42_sol] = ...
            expH3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10,0.5);

        expH42_err(i) = ...
            norm(exac_sol-expH42_sol(:),'inf');

        % ----------------------------------------------------
        % expH4s3
        % ----------------------------------------------------
        [~,expH4s3_sol] = ...
            expH4s3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N(i), ...
                1e-10,[0.35,0.8]);

        expH4s3_err(i) = ...
            norm(exac_sol-expH4s3_sol(:),'inf');

        fprintf('epsilon = %.3f, N = %d done\n', ...
            epsilon,N(i));

    end

    % ========================================================
    % Compute observed convergence orders
    % ========================================================
    expHR3_order = ...
        log(expHR3_err(1:end-1)./expHR3_err(2:end))/log(2);

    expHR42_order = ...
        log(expHR42_err(1:end-1)./expHR42_err(2:end))/log(2);

    expHR4s3_order = ...
        log(expHR4s3_err(1:end-1)./expHR4s3_err(2:end))/log(2);

    expH3_order = ...
        log(expH3_err(1:end-1)./expH3_err(2:end))/log(2);

    expH42_order = ...
        log(expH42_err(1:end-1)./expH42_err(2:end))/log(2);

    expH4s3_order = ...
        log(expH4s3_err(1:end-1)./expH4s3_err(2:end))/log(2);

    expRB32_order = ...
        log(expRB32_err(1:end-1)./expRB32_err(2:end))/log(2);

    expRB42_order = ...
        log(expRB42_err(1:end-1)./expRB42_err(2:end))/log(2);

    expRB43_order = ...
        log(expRB43_err(1:end-1)./expRB43_err(2:end))/log(2);

    pexpRB43_order = ...
        log(pexpRB43_err(1:end-1)./pexpRB43_err(2:end))/log(2);

    % ========================================================
    % Save all numerical data
    % ========================================================
    % data_file = fullfile( ...
    %     results_dir, ...
    %     ['Allencahn_data_128_eps_' eps_names{k} '.mat']);
    % 
    % save(data_file, ...
    %     'epsilon', ...
    %     'N', ...
    %     'h', ...
    %     'n', ...
    %     'dx', ...
    %     'dy', ...
    %     'tspan', ...
    %     'expHR3_err', ...
    %     'expHR42_err', ...
    %     'expHR4s3_err', ...
    %     'expH3_err', ...
    %     'expH42_err', ...
    %     'expH4s3_err', ...
    %     'expRB32_err', ...
    %     'expRB42_err', ...
    %     'expRB43_err', ...
    %     'pexpRB43_err', ...
    %     'expHR3_order', ...
    %     'expHR42_order', ...
    %     'expHR4s3_order', ...
    %     'expH3_order', ...
    %     'expH42_order', ...
    %     'expH4s3_order', ...
    %     'expRB32_order', ...
    %     'expRB42_order', ...
    %     'expRB43_order', ...
    %     'pexpRB43_order');
    % 
    % fprintf('\nNumerical data saved to:\n%s\n',data_file);

    % ========================================================
    % Display errors and orders
    % ========================================================
    fprintf('\n=============================================\n');
    fprintf('Errors for epsilon = %.3f\n',epsilon);
    fprintf('=============================================\n');

    fprintf('\nN = ');
    fprintf('%12d',N);
    fprintf('\n');

    fprintf('expHR3   = ');
    fprintf('%12.4e',expHR3_err);
    fprintf('\n');

    fprintf('expHR42  = ');
    fprintf('%12.4e',expHR42_err);
    fprintf('\n');

    fprintf('expHR4s3 = ');
    fprintf('%12.4e',expHR4s3_err);
    fprintf('\n');

    fprintf('expH3    = ');
    fprintf('%12.4e',expH3_err);
    fprintf('\n');

    fprintf('expH42   = ');
    fprintf('%12.4e',expH42_err);
    fprintf('\n');

    fprintf('expH4s3  = ');
    fprintf('%12.4e',expH4s3_err);
    fprintf('\n');

    fprintf('expRB32  = ');
    fprintf('%12.4e',expRB32_err);
    fprintf('\n');

    fprintf('expRB42  = ');
    fprintf('%12.4e',expRB42_err);
    fprintf('\n');

    fprintf('expRB43  = ');
    fprintf('%12.4e',expRB43_err);
    fprintf('\n');

    fprintf('pexpRB43 = ');
    fprintf('%12.4e',pexpRB43_err);
    fprintf('\n');

    % ========================================================
    % Convergence plot
    % ========================================================
    fig = figure(k);

    set(fig,'Units','inches');
    set(fig,'Position',[1 1 6.8 5.2]);
    set(fig,'PaperPositionMode','auto');

    loglog( ...
        h,expHR3_err, ...
        'o-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    hold on

    loglog( ...
        h,expHR42_err, ...
        'o-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expHR4s3_err, ...
        'v-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expH3_err, ...
        '>-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expH42_err, ...
        '>-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expH4s3_err, ...
        '<-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expRB32_err, ...
        '^-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expRB42_err, ...
        '^-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expRB43_err, ...
        'd-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,pexpRB43_err, ...
        's-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    % Reference slopes
    loglog( ...
        h,h.^3*800, ...
        '--', ...
        'LineWidth',1);

    loglog( ...
        h,h.^4*80, ...
        '--', ...
        'LineWidth',1);

    % --------------------------------------------------------
    % Axis labels
    % --------------------------------------------------------
    xlabel('Number of time steps')
    ylabel('Error')

    grid on
    box on

    % --------------------------------------------------------
    % Axis settings
    % --------------------------------------------------------
    ax = gca;

    ax.Units = 'normalized';
    ax.Position = [0.24 0.16 0.72 0.72];

    set(ax, ...
        'TickLength', ...
        2*get(ax,'TickLength'));

    axis square

    % --------------------------------------------------------
    % Legend
    % --------------------------------------------------------
    lgd = legend( ...
            'expHR3s2', ...
            'expHR4s2', ...
            'expHR4s3', ...
            'expH3', ...
            'expH4s2', ...
            'expH4s3', ...
            'exprb32', ...
            'exprb42', ...
            'exprb43', ...
            'pexprb43', ...
            'Slope 3', ...
            'Slope 4', ...
            'Location','westoutside');

        lgd.FontSize = 10;

    % --------------------------------------------------------
    % X-axis
    %
    % h = [1/32 1/64 1/128 1/256]
    % labels represent number of time steps
    % --------------------------------------------------------
    set(ax,'XTick',fliplr(h));

    xticklabels( ...
        string(fliplr(N)));

    % --------------------------------------------------------
    % Plot limits
    % --------------------------------------------------------
   min_err = [ ...
    min(expHR3_err), ...
    min(expHR42_err), ...
    min(expHR4s3_err), ...
    min(expH3_err), ...
    min(expH42_err), ...
    min(expH4s3_err), ...
    min(expRB32_err), ...
    min(expRB42_err), ...
    min(expRB43_err), ...
    min(pexpRB43_err)];
   max_err = [ ...
    max(expHR3_err), ...
    max(expHR42_err), ...
    max(expHR4s3_err), ...
    max(expH3_err), ...
    max(expH42_err), ...
    max(expH4s3_err), ...
    max(expRB32_err), ...
    max(expRB42_err), ...
    max(expRB43_err), ...
    max(pexpRB43_err) ];
    axis([ ...
        1/256 ...
        1/32 ...
        min(min_err) ...
        max(max_err)]);

    % --------------------------------------------------------
    % Y-axis ticks
    % --------------------------------------------------------
    yt = [ ...
        1e-12, ...
        1e-11, ...
        1e-10, ...
        1e-9, ...
        1e-8, ...
        1e-7, ...
        1e-6, ...
        1e-5, ...
        1e-4, ...
        1e-3, ...
        1e-2, ...
        1e-1];

    set(ax,'YTick',yt);

    % ========================================================
    % Save figure
    % ========================================================
    fig_base = fullfile( ...
        results_dir, ...
        ['Allencahn_Order34_128_eps_' eps_names{k}]);

    % EPS for paper
    print( ...
        fig, ...
        fig_base, ...
        '-depsc');

    fprintf('\nFigures saved to:\n%s\n',results_dir);

end

% ============================================================
% Remove temporary paths
% ============================================================
rmpath( ...
    '../integrators', ...
    '../phipmsimuliom', ...
    './Data');

fprintf('\n=============================================\n');
fprintf('All computations finished.\n');
fprintf('Results are stored in:\n');
fprintf('%s\n',results_dir);
fprintf('=============================================\n');