clc
clear
close all

% ============================================================
% Add required folders to MATLAB path
% ============================================================
addpath('../integrators','../phipmsimuliom','./Data')

% ============================================================
% Results folder
% ============================================================
results_dir = './Test_results';

if ~exist(results_dir,'dir')
    mkdir(results_dir);
end

% ============================================================
% Parameters
% ============================================================
eps_list  = [0.015];
eps_names = {'0_015'};

N = [16,32,64,128].*2;
h = 1./N;

% ============================================================
% Loop over epsilon
% ============================================================
for k = 1:length(eps_list)

    epsilon = eps_list(k);

    fprintf('\n==============================\n');
    fprintf('Running for epsilon = %.3f\n',epsilon);
    fprintf('==============================\n');

    % --------------------------------------------------------
    % Time interval
    % --------------------------------------------------------
    s = 3/(sqrt(2)*epsilon);
    tspan = [0,3/(4*s)];

    % --------------------------------------------------------
    % Space discretization on Omega = [-0.5,1.5]^2
    % --------------------------------------------------------
    n  = 128;

    xL = -0.5;
    xR = 1.5;

    yL = -0.5;
    yR = 1.5;

    dx = (xR-xL)/n;
    dy = (yR-yL)/n;

    x = linspace(xL,xR,n+1);
    y = linspace(yL,yR,n+1);

    [X,Y] = meshgrid(x,y);

    X = X';
    Y = Y';

    % ========================================================
    % Initial condition
    % ========================================================
    initial_condition = ...
        0.5*(1-tanh(X/(2*sqrt(2)*epsilon)));

    U0 = reshape( ...
        initial_condition, ...
        (n+1)*(n+1),1);

    % ========================================================
    % Nonlinearity
    % ========================================================
    g = @(u) ...
        (1/epsilon^2)*u ...
        - (1/epsilon^2)*u.^3;

    deriv_g = @(u) ...
        (1/epsilon^2) ...
        - 3*(1/epsilon^2)*u.^2;

    % ========================================================
    % Spatial discretization
    % ========================================================
    I = speye(n+1);
    e = ones(n+1,1);

    % --------------------------------------------------------
    % 1D Neumann Laplacian
    % --------------------------------------------------------
    Tx = spdiags( ...
        [e -2*e e], ...
        [-1 0 1], ...
        n+1,n+1);

    Tx(1,2)       = 2;
    Tx(end,end-1) = 2;

    Ty = spdiags( ...
        [e -2*e e], ...
        [-1 0 1], ...
        n+1,n+1);

    Ty(1,2)       = 2;
    Ty(end,end-1) = 2;

    % --------------------------------------------------------
    % 2D Laplacian with zero Neumann BC
    % --------------------------------------------------------
    A = kron(I,Tx)/dx^2 ...
      + kron(Ty,I)/dy^2;

    % ========================================================
    % Semilinear system
    % ========================================================
    F = @(u) A*u + g(u);

    J = @(u) ...
        spdiags( ...
            deriv_g(u), ...
            0, ...
            (n+1)^2, ...
            (n+1)^2);

    % ========================================================
    % Load exact/reference solution
    % ========================================================
    fname = ...
        ['128_exac_sol_AllenCahn_' eps_names{k} '.mat'];

    data_fname = fullfile('./Data',fname);

    if exist(data_fname,'file')
        S = load(data_fname);
    else
        S = load(fname);
    end

    if isfield(S,'exac_sol')

        exac_sol = S.exac_sol;

    else

        vars = fieldnames(S);
        exac_sol = S.(vars{1});

    end

    % Make sure exact solution is a column vector
    exac_sol = exac_sol(:);

    % ========================================================
    % Preallocate errors
    % ========================================================
    expHR5s5_err  = zeros(1,length(N));
    expHR5s4_err  = zeros(1,length(N));
    expHR5s4a_err = zeros(1,length(N));
    expHR5s3_err  = zeros(1,length(N));
    expHR5s3a_err = zeros(1,length(N));

    pexpRB55_err  = zeros(1,length(N));
    pexpRB54_err  = zeros(1,length(N));
    expRB53_err   = zeros(1,length(N));

    % ========================================================
    % Preallocate CPU times
    % ========================================================
    expHR5s5_cpu  = zeros(1,length(N));
    expHR5s4_cpu  = zeros(1,length(N));
    expHR5s4a_cpu = zeros(1,length(N));
    expHR5s3_cpu  = zeros(1,length(N));
    expHR5s3a_cpu = zeros(1,length(N));

    pexpRB55_cpu  = zeros(1,length(N));
    pexpRB54_cpu  = zeros(1,length(N));
    expRB53_cpu   = zeros(1,length(N));

    % ========================================================
    % Number of time steps
    % ========================================================
    N_expHR5s5  = N;
    N_expHR5s4  = N;
    N_expHR5s4a = N;
    N_expHR5s3  = N;
    N_expHR5s3a = N;

    N_pexpRB55 = N;
    N_pexpRB54 = N;
    N_expRB53  = N;

    % ========================================================
    % Time integration
    % ========================================================
    for i = 1:length(N)

        fprintf('\n-----------------------------------\n');
        fprintf('epsilon = %.3f, N = %d\n', ...
            epsilon,N(i));
        fprintf('-----------------------------------\n');

        % ----------------------------------------------------
        % expHR5s5
        % ----------------------------------------------------
        [~,expHR5s5_sol,expHR5s5_cpu(i)] = ...
            expHR5s5( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expHR5s5(i), ...
                1e-10,0.3);

        expHR5s5_err(i) = ...
            norm(exac_sol-expHR5s5_sol(:),'inf');

        % ----------------------------------------------------
        % expHR5s3
        % ----------------------------------------------------
        [~,expHR5s3_sol,expHR5s3_cpu(i)] = ...
            expHR5s3( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expHR5s3(i), ...
                1e-10,0.3);

        expHR5s3_err(i) = ...
            norm(exac_sol-expHR5s3_sol(:),'inf');

        % ----------------------------------------------------
        % expHR5s3a
        % ----------------------------------------------------
        [~,expHR5s3a_sol,expHR5s3a_cpu(i)] = ...
            expHR5s3a( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expHR5s3a(i), ...
                1e-10,0.3);

        expHR5s3a_err(i) = ...
            norm(exac_sol-expHR5s3a_sol(:),'inf');

        % ----------------------------------------------------
        % expHR5s4
        % ----------------------------------------------------
        [~,expHR5s4_sol,expHR5s4_cpu(i)] = ...
            expHR5s4( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expHR5s4(i), ...
                1e-10,0.1);

        expHR5s4_err(i) = ...
            norm(exac_sol-expHR5s4_sol(:),'inf');

        % ----------------------------------------------------
        % expHR5s4a
        % ----------------------------------------------------
        [~,expHR5s4a_sol,expHR5s4a_cpu(i)] = ...
            expHR5s4a( ...
                F,A,J, ...
                0,tspan(2), ...
                U0,N_expHR5s4a(i), ...
                1e-10,0.1);

        expHR5s4a_err(i) = ...
            norm(exac_sol-expHR5s4a_sol(:),'inf');

        % ----------------------------------------------------
        % expRB53
        % ----------------------------------------------------
        [~,expRB53_sol,expRB53_cpu(i)] = ...
            expRB53( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N_expRB53(i), ...
                1e-10);

        expRB53_err(i) = ...
            norm(exac_sol-expRB53_sol(:),'inf');

        % ----------------------------------------------------
        % pexpRB54
        % ----------------------------------------------------
        [~,pexpRB54_sol,pexpRB54_cpu(i)] = ...
            pexpRB54( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N_pexpRB54(i), ...
                1e-10);

        pexpRB54_err(i) = ...
            norm(exac_sol-pexpRB54_sol(:),'inf');

        % ----------------------------------------------------
        % pexpRB55
        % ----------------------------------------------------
        [~,pexpRB55_sol,pexpRB55_cpu(i)] = ...
            pexpRB55( ...
                F,A,g,J, ...
                0,tspan(2), ...
                U0,N_pexpRB55(i), ...
                1e-10);

        pexpRB55_err(i) = ...
            norm(exac_sol-pexpRB55_sol(:),'inf');

        fprintf('epsilon = %.3f, N = %d done\n', ...
            epsilon,N(i));

    end

    % ========================================================
    % Observed convergence orders
    % ========================================================
    expHR5s5_order = ...
        log(expHR5s5_err(1:end-1)./expHR5s5_err(2:end))/log(2);

    expHR5s4_order = ...
        log(expHR5s4_err(1:end-1)./expHR5s4_err(2:end))/log(2);

    expHR5s4a_order = ...
        log(expHR5s4a_err(1:end-1)./expHR5s4a_err(2:end))/log(2);

    expHR5s3_order = ...
        log(expHR5s3_err(1:end-1)./expHR5s3_err(2:end))/log(2);

    expHR5s3a_order = ...
        log(expHR5s3a_err(1:end-1)./expHR5s3a_err(2:end))/log(2);

    pexpRB55_order = ...
        log(pexpRB55_err(1:end-1)./pexpRB55_err(2:end))/log(2);

    pexpRB54_order = ...
        log(pexpRB54_err(1:end-1)./pexpRB54_err(2:end))/log(2);

    expRB53_order = ...
        log(expRB53_err(1:end-1)./expRB53_err(2:end))/log(2);

    % ========================================================
    % Minimum errors
    % ========================================================
    min_err = [ ...
        min(expHR5s5_err), ...
        min(expHR5s4_err), ...
        min(expHR5s4a_err), ...
        min(expHR5s3_err), ...
        min(expHR5s3a_err), ...
        min(pexpRB55_err), ...
        min(pexpRB54_err), ...
        min(expRB53_err) ...
    ];

    % ========================================================
    % Maximum errors
    % ========================================================
    max_err = [ ...
        max(expHR5s5_err), ...
        max(expHR5s4_err), ...
        max(expHR5s4a_err), ...
        max(expHR5s3_err), ...
        max(expHR5s3a_err), ...
        max(pexpRB55_err), ...
        max(pexpRB54_err), ...
        max(expRB53_err) ...
    ];

    % ========================================================
    % Save all numerical data
    % ========================================================
    data_file = fullfile( ...
        results_dir, ...
        ['Allencahn_Order5_data_128_eps_' eps_names{k} '.mat']);

    save(data_file, ...
        'epsilon', ...
        'n', ...
        'dx', ...
        'dy', ...
        'tspan', ...
        'N', ...
        'h', ...
        ...
        'N_expHR5s5', ...
        'N_expHR5s4', ...
        'N_expHR5s4a', ...
        'N_expHR5s3', ...
        'N_expHR5s3a', ...
        'N_pexpRB55', ...
        'N_pexpRB54', ...
        'N_expRB53', ...
        ...
        'expHR5s5_err', ...
        'expHR5s4_err', ...
        'expHR5s4a_err', ...
        'expHR5s3_err', ...
        'expHR5s3a_err', ...
        'pexpRB55_err', ...
        'pexpRB54_err', ...
        'expRB53_err', ...
        ...
        'expHR5s5_cpu', ...
        'expHR5s4_cpu', ...
        'expHR5s4a_cpu', ...
        'expHR5s3_cpu', ...
        'expHR5s3a_cpu', ...
        'pexpRB55_cpu', ...
        'pexpRB54_cpu', ...
        'expRB53_cpu', ...
        ...
        'expHR5s5_order', ...
        'expHR5s4_order', ...
        'expHR5s4a_order', ...
        'expHR5s3_order', ...
        'expHR5s3a_order', ...
        'pexpRB55_order', ...
        'pexpRB54_order', ...
        'expRB53_order', ...
        ...
        'min_err', ...
        'max_err');

    fprintf('\nNumerical data saved to:\n%s\n',data_file);

    % ========================================================
    % Display min/max errors
    % ========================================================
    method_names = { ...
        'expHR5s5', ...
        'expHR5s4', ...
        'expHR5s4a', ...
        'expHR5s3', ...
        'expHR5s3a', ...
        'pexpRB55', ...
        'pexpRB54', ...
        'expRB53'};

    fprintf('\n=============================================\n');
    fprintf('Order-5 results for epsilon = %.3f\n',epsilon);
    fprintf('=============================================\n');

    fprintf('\nMethod          Min Error       Max Error\n');
    fprintf('---------------------------------------------\n');

    for j = 1:length(method_names)

        fprintf('%-12s  %12.4e   %12.4e\n', ...
            method_names{j}, ...
            min_err(j), ...
            max_err(j));

    end

    % ========================================================
    % Order plot
    % ========================================================
    fig = figure(k);

    set(fig,'Units','inches');
    set(fig,'Position',[1 1 6.8 5.2]);
    set(fig,'PaperPositionMode','auto');

    loglog( ...
        h,expHR5s5_err, ...
        'o-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    hold on

    loglog( ...
        h,expHR5s4_err, ...
        '*-', ...
        'LineWidth',1, ...
        'MarkerSize',12);

    loglog( ...
        h,expHR5s4a_err, ...
        '*-', ...
        'LineWidth',1, ...
        'MarkerSize',12);

    loglog( ...
        h,expHR5s3_err, ...
        'v-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expHR5s3a_err, ...
        'v-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,pexpRB55_err, ...
        '>-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,pexpRB54_err, ...
        '^-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    loglog( ...
        h,expRB53_err, ...
        '<-', ...
        'LineWidth',1, ...
        'MarkerSize',10);

    % Reference slope 5
    loglog( ...
        h,h.^5*80, ...
        '--', ...
        'LineWidth',1);

    % ========================================================
    % Labels
    % ========================================================
    xlabel('Number of time steps')
    ylabel('Error')

    grid on
    box on

    % ========================================================
    % Axis settings
    % ========================================================
    ax = gca;

    ax.Units = 'normalized';
    ax.Position = [0.24 0.16 0.72 0.72];

    set(ax, ...
        'TickLength', ...
        2*get(ax,'TickLength'));

    axis square

    % ========================================================
    % Legend
    % ========================================================
    if k == length(eps_list)

        lgd = legend( ...
            'expHR5s5', ...
            'expHR5s4', ...
            'expHR5s4a', ...
            'expHR5s3', ...
            'expHR5s3a', ...
            'pexprb55', ...
            'pexprb54', ...
            'exprb53', ...
            'Slope 5', ...
            'Location','westoutside');

        lgd.FontSize = 10;

    else

        legend off

    end

    % ========================================================
    % X-axis
    % ========================================================
    set(ax,'XTick',fliplr(h));

    xticklabels(string(fliplr(N)));

    % ========================================================
    % Axis limits
    % ========================================================
    axis([ ...
        1/256 ...
        1/32 ...
        2.226584472353466e-10 ...
        4.565554093939328e-04]);

    % ========================================================
    % Y-axis ticks
    % ========================================================
    yt = [ ...
        1e-12, ...
        1e-11, ...
        1e-10, ...
        1e-9, ...
        1e-8, ...
        1e-7, ...
        1e-6, ...
        1e-5, ...
        1e-4, ...
        1e-3, ...
        1e-2, ...
        1e-1];

    set(ax,'YTick',yt);

    % ========================================================
    % Save figures
    % ========================================================
    fig_base = fullfile( ...
        results_dir, ...
        ['Allencahn_Order5_128_eps_' eps_names{k}]);

    % EPS
    print( ...
        fig, ...
        fig_base, ...
        '-depsc');

 

    fprintf('\nFigures saved to:\n%s\n',results_dir);

end

% ============================================================
% Remove paths
% ============================================================
rmpath( ...
    '../integrators', ...
    '../phipmsimuliom', ...
    './Data');

fprintf('\n=============================================\n');
fprintf('All order-5 computations finished.\n');
fprintf('Results are stored in:\n');
fprintf('%s\n',results_dir);
fprintf('=============================================\n');